### PR TITLE
Add support for the Aquacomputer Quadro

### PR DESCRIPTION
**Pull request by JackDoan**
I tried to keep the changes to the absolute minimum, but I feel like there's refactoring opportunities to simplify things a little bit (like defining a number of fans/sensors/etc in `struct aqc_data`). Lmk if you'd like to see that done, or if you think this change would be easier to mainline as is.

Thanks!

### CODE REVIEW

**Comment by aleksamagicka** [comment]
Hi! Excellent, thanks 😄

Sorry for not being so active on the other PR, I definitely want to merge it & get it to mainline, it's just that I'm overwhelmed with college work & exams these months.

Regarding the refactoring PR, I think that's definitely something we should do.

I've got a Quadro on its way to me, which should arrive soon, so I'll test your other PR then. For the Farbwerk, I'll pull it and send it to hwmon since the additions are very simple, just to get it in for 5.19. I think the refactoring can come after it, and if it's accepted, we can just elegantly add in the Quadro.

I'm thinking of adding you as a maintainer for the mainline hwmon driver, is that OK with you?

**Comment by aleksamagicka** [comment]
Great, thanks! I'll do it till the end of this week.

**Comment by aleksamagicka** [comment]
I've tested this, checked all fans and sensors and everything works great 👍 

Will test the refactored PR next.

**Comment by JackDoan** [comment]
Closing this in favor of #5 's approach

**Pull request closed without merging**
