### PR TITLE
hwmon: (aquacomputer_d5next) Add support for Aquacomputer Leakshield

### PR DESCRIPTION
**Pull request by aleksamagicka**
@main--, please test and review, if possible. This patch covers the sensors of the Leakshield, writing will come later. Thanks!

### CODE REVIEW

**Comment by main--** [comment]
I did a quick test and the only difference I can find is that this value:

```
Pressure [µbar]:          382300 RPM  (min = 85900 RPM, max = 465000 RPM)
```

changes when I `make dev` this branch:

```
Pressure [ubar]:           54720 RPM  (min = 85900 RPM, max = 465000 RPM)
```

I'm guessing that 54 mbar might be the target pressure, but it is definitely not the actual pressure (which is 382mbar, as shown above and on the device display as well).

**Comment by aleksamagicka** [comment]
Thanks, I'll take a look. One thing I just fixed is that `speed_input[8]` was an u16, it's now a s32.

**Comment by aleksamagicka** [comment]
The rest of the code looks the same. I'm pretty sure it overflowed with just an u16, here's a test:

```
u16 test = 382300;
```

The compiler immediately notices:

```
warning: unsigned conversion from ‘int’ to ‘u16’ {aka ‘short unsigned int’} changes value from ‘382300’ to ‘54620’ [-Woverflow]
 1433 |         u16 test = 382300;
      |                    ^~~~~~
```

Which is very close to the value you're getting, depending on the moment of capture.

**Comment by aleksamagicka** [comment]
Great, thanks!

**Comment by aleksamagicka** [comment]
This made it in, merging.

**Pull request merged**
