### PR TITLE
Leakshield: send flow rate correctly

### PR DESCRIPTION
**Pull request by main--**
As reported in https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/pull/41#issuecomment-1287897611.

@hp-pepster can you confirm if this fixes the issue for you?

### CODE REVIEW

**Comment by hp-pepster** [comment]
Yes, it does. Thank you very much.

**Comment by main--** [comment]
@aleksamagicka I'm pretty hopeful that I understand the structure of the HID report now:

```c
struct leakshield_hid_report {
    u8 unknown; // 4
    u16/*BE*/ sensor_values[16];
    u8 sensor_units[16]; // RPM=3, dL/h=0xC, other units currently unknown
    u16/*BE*/ checksum;
};
```

With some luck. it works the same way (or close to it) for other devices as well.

**Comment by hp-pepster** [comment]
Has someone tried to get some info from Aquacomputer regarding the USB protocol? Maybe they are willing to help at least with that information (although they don't want to provide a consumer software for unix).
If not I can ask them, the worst that could happen is to get a "no".

**Comment by aleksamagicka** [comment]
@main--: `4` is the HID report ID. Thanks for the quick turnaround!

@hp-pepster: Before I even started writing the driver, I looked up their forums to check for any clues regarding the HID structures, and I found official answers ranging from "no, too low of a usershare for the effort" (meh, OK) to pretty much (caps lock) "WHAT? Nope, then we'd have to support the docs for the structures as well". Make your own conclusions...

There is/was a Python program for the Aquaero, and IIRC the author of that received some Aquaeros from the company to help him reverse engineer that. They really do not want to part with the structure info.

**Pull request merged**
