### PR TITLE
Cache control report

### PR DESCRIPTION
**Pull request by leoratte**
Implements a cache for the control buffer by not reading the control
report for every control value. The cache is used by calling
aqc_get_control_val() and setting the refresh parameter to false.

This caching feature reduces the amount of requests to the device.
Especially aquaero needed eight requests when using 'sensors' which is
now reduced to one.

Additionally control and sensor buffer are split to avoid confusion.

### CODE REVIEW

**Comment by aleksamagicka** [comment]
The problem I see with this is that the driver can happen to end up with stale data (or a race condition of sorts, if writing something) if userspace is sending its own stuff to the device using hidraw. Unlikely, but possible, and not what we want, similarly to #43.

Writes, especially for aquaero, are already optimized thanks to your work on `aqc_set_ctrl_vals()` in #47. Did you maybe notice the aquaero rejecting the requests or something else, so that caching this way would be needed?

**Comment by leoratte** [comment]
I know of the problem with possibly stale data but I don't see another solution to reducing the number of requests to the device. I have not seen any problems with too many requests at once, but we should keep that in mind for the future.

I'm ok with not merging the control report cache part. What do you think about separating control and sensors report buffers for better understandability?

**Comment by aleksamagicka** [comment]
Sorry for the delay, I'll look into it and let you know.

**Comment by aleksamagicka** [comment]
I don't see the need for separate buffers. In the case of legacy devices, if we request a sensor report, the related fields in the struct are populated and the buffer contents become irrelevant. If we're writing anything, after the write is complete the buffer contents again do not matter and will be refreshed next time. So, in either case we don't need to keep one separate from the other.

However, I do agree that this behaviour should be noted - I'll add a comment.

---
Closing this PR for now. Please reopen (or create an issue) if you notice the devices drop reports under 'stress'.

**Pull request closed without merging**
