### PR TITLE
added support for the flow sensor on quadro

### PR DESCRIPTION
**Pull request by leoratte**
I have added support for the flow sensor for the quadro. I simply put the flow speed in the 5th fan speed place.
I have only tested it with the quadro and hope it does not break for other devices. It should be easy to adapt for the octo.

```
quadro-hid-3-3
Adapter: HID adapter
Fan 1 voltage:     12.13 V  
Fan 2 voltage:     12.13 V  
Fan 3 voltage:     12.13 V  
Fan 4 voltage:     12.13 V  
Fan 1 speed:       643 RPM
Fan 2 speed:      1756 RPM
Fan 3 speed:       659 RPM
Fan 4 speed:       650 RPM
Flow speed [l/h]:   60 RPM
Sensor 1:          +33.9°C  
Sensor 2:          +25.3°C  
Sensor 3:          +37.6°C  
Sensor 4:          +33.3°C  
Fan 1 power:      290.00 mW 
Fan 2 power:        0.00 W  
Fan 3 power:      260.00 mW 
Fan 4 power:      260.00 mW 
Fan 1 current:     24.00 mA 
Fan 2 current:      0.00 A  
Fan 3 current:     22.00 mA 
Fan 4 current:     22.00 mA

```

### CODE REVIEW

**Comment by aleksamagicka** [comment]
Thanks!

**Comment by aleksamagicka** [comment]
@leoratte, I'm preparing a patch for mainline which adds support for Quadro. Can you please give me your email, so I can credit you in the patch?

**Comment by leoratte** [comment]
Sure, please use leonard.anderweit[at]gmail.com. I hope they accept re-purposing the fan speed for the flow speed.

**Comment by aleksamagicka** [comment]
Thanks. I believe using RPM for flow speed is fine, some of the existing drivers do that ([example](https://elixir.bootlin.com/linux/v5.19-rc8/source/drivers/hwmon/asus_wmi_sensors.c#L126)), and we note it with a label.

**Pull request merged**
