### PR TITLE
Add sysfs entry temp_offset

### PR DESCRIPTION
**Pull request by leoratte**
Adds the sysfs entry temp_offset, which allows to set a correction offset for each temperature sensor.

- [ ]  Find and add control offsets for the other devices

### CODE REVIEW

**Comment by leoratte** [comment]
Improved upon your suggestions. The label was missing, as it was no longer visible.

**Comment by aleksamagicka** [comment]
Ah I see, that was it. Didn't look at the code very deeply yesterday, just tested.

LGTM now, I'll try to RE the offsets for other devices in the upcoming days.

**Comment by aleksamagicka** [comment]
Here are the offsets for other devices I have:

- Farbwerk 360: temp offsets start at `0x08`, control report size is `0x68A`.
- Octo: temp offsets start at `0xa`, same as Quadro.
- D5 Next: temp offsets start at `0x16`.

**Comment by aleksamagicka** [comment]
Sorry, I've made two mistakes regarding the offsets - Farbwerk 360 control report size is `0x682`, and D5 Next temp offset is actually `0x2D`.

Please mark it as ready to review when you think you're done it with, and I'll merge and send to mainline.

**Review by aleksamagicka — APPROVED** [review]

**Comment by aleksamagicka** [comment]
Thanks!

**Pull request merged**
