### PR TITLE
Add more sensors for poweradjust3

### PR DESCRIPTION
**Pull request by leoratte**
This PR adds the following new sensors for poweradjust3.
- Internal temperature sensors for the fan control IC
- RPM, voltage and current for the connected fan
- One flow meter

### Checklist:

- [x] My code follows Linux code style guidelines
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have tested my changes on the affected device(s) - Poweradjust 3
- [x] All exposed values are being read from the device

### CODE REVIEW

**Comment by aleksamagicka** [comment]
Thanks!! Will look at this and the other PR(s) ASAP.

**Review by aleksamagicka — APPROVED** [review]
LGTM! Love the commit titles.

Does setting the fan speed work maybe?

**Comment by leoratte** [comment]
Changing the fan speed probably works, but so far if only collected the control reports and the relevant offsets. I'll look into implementing fan control over the weekend.

**Comment by aleksamagicka** [comment]
Can I merge this for now (so that I can submit to LKML)?

**Comment by leoratte** [comment]
Please wait with merging for. I want to Look into the flow Sensor again as I suspect there ist something wrong.
For the Fan Control I'll open a separate PR because it depends on #91.

**Comment by leoratte** [comment]
Just checked the flow sensor again and everything looks good.

**Comment by aleksamagicka** [comment]
Thanks!

**Pull request merged**
