### PR TITLE
add sysfs entry pwm_auto_channels_temp

### PR DESCRIPTION
**Pull request by leoratte**
Adds the sysfs entry pwm_auto_channels_temp which allows to select the temperature sensor for the automatic control modes (PID control mode + fan curve mode).

### CODE REVIEW

**Comment by leoratte** [comment]
The check fails because pwm_auto_channels_temp was first introduced in kernel 5.18 and the check uses kernel 5.15.

**Comment by leoratte** [comment]
The build check now uses https://github.com/torvalds/linux as linux kernel source to compile the driver.

**Comment by aleksamagicka** [comment]
Thanks, I'll look over in a few days.

**Comment by leoratte** [comment]
Can you reopen. I accidentally pushed main into this.

**Comment by aleksamagicka** [comment]
It says there are no new commits on your branch and I can't reopen it, though I [see the commits?](https://github.com/leoratte/aquacomputer_d5next-hwmon/commits/pwm_auto_channels_temp) Try making a new PR, that should work.

**Pull request closed without merging**
