### PR TITLE
highflownext: proper offset for flow is 81

### PR DESCRIPTION
**Pull request by dankamongmen**
Determined via experiment that the flow is reported as a 16-bit big-endian value at the 81st byte, not the 75th. Output now matches the device display exactly, except that it's scaled by 10x (i.e. the device shows 214.7, and hwmon shows 2147). Per our discussion in #33, I understand you prefer to keep it this way, reporting it as an integer RPM value. I have thus done so.

### CODE REVIEW

**Comment by dankamongmen** [comment]
for future reference, here's the data as collected by the module. samples are one second apart. first column is UEFI set to "silent", second column is UEFI sent to "max speed" for my pumps.

```
Sep 02 16:10:09 schwarzgerat kernel: [000] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [001] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [002] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [003] 05 05 05 05 05 05 05 05    05 05 05 05 05 05 05 05
Sep 02 16:10:09 schwarzgerat kernel: [004] 91 91 91 91 91 91 91 91    91 91 91 91 91 91 91 91
Sep 02 16:10:09 schwarzgerat kernel: [005] 7f 7f 7f 7f 7f 7f 7f 7f    7f 7f 7f 7f 7f 7f 7f 7f
Sep 02 16:10:09 schwarzgerat kernel: [006] 77 77 77 77 77 77 77 77    77 77 77 77 77 77 77 77
Sep 02 16:10:09 schwarzgerat kernel: [007] 03 03 03 03 03 03 03 03    03 03 03 03 03 03 03 03
Sep 02 16:10:09 schwarzgerat kernel: [008] e8 e8 e8 e8 e8 e8 e8 e8    e8 e8 e8 e8 e8 e8 e8 e8
Sep 02 16:10:09 schwarzgerat kernel: [009] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [010] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [011] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [012] 64 64 64 64 64 64 64 64    64 64 64 64 64 64 64 64
Sep 02 16:10:09 schwarzgerat kernel: [013] 03 03 03 03 03 03 03 03    03 03 03 03 03 03 03 03
Sep 02 16:10:09 schwarzgerat kernel: [014] f8 f8 f8 f8 f8 f8 f8 f8    f8 f8 f8 f8 f8 f8 f8 f8
Sep 02 16:10:09 schwarzgerat kernel: [015] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [016] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [017] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [018] f2 f2 f2 f2 f2 f2 f2 f2    f2 f2 f2 f2 f2 f2 f2 f2
Sep 02 16:10:09 schwarzgerat kernel: [019] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [020] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [021] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [022] 28 28 28 29 29 29 29 29    47 47 48 48 48 48 48 48
Sep 02 16:10:09 schwarzgerat kernel: [023] e3 ed f7 01 0b 16 20 2a    f0 fa 0e 18 22 2c 36 41
Sep 02 16:10:09 schwarzgerat kernel: [024] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [025] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [026] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [027] da da da da da da da da    da da da da da da da da
Sep 02 16:10:09 schwarzgerat kernel: [028] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [029] 68 68 68 68 68 68 68 68    68 68 68 68 68 68 68 68
Sep 02 16:10:09 schwarzgerat kernel: [030] 65 65 65 65 65 65 65 65    65 65 65 65 65 69 69 69
Sep 02 16:10:09 schwarzgerat kernel: [031] 49 49 49 49 49 49 49 49    49 49 49 49 49 f9 f9 f9
Sep 02 16:10:09 schwarzgerat kernel: [032] 38 38 38 38 38 38 39 39    9f 9f a0 a0 a0 a0 a0 a0
Sep 02 16:10:09 schwarzgerat kernel: [033] 3d 5e 80 a2 c3 e5 07 28    bc de 21 43 65 86 a8 ca
Sep 02 16:10:09 schwarzgerat kernel: [034] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [035] a2 a2 a2 a2 a2 a2 a2 a2    a3 a3 a3 a3 a3 a3 a3 a4
Sep 02 16:10:09 schwarzgerat kernel: [036] 3d 3d 3d 3d 3d 3d 3d 3e    ef f1 f6 f8 fb fd ff 02
Sep 02 16:10:09 schwarzgerat kernel: [037] a2 a2 a2 a2 a2 a2 a2 a2    a3 a3 a3 a3 a3 a3 a3 a3
Sep 02 16:10:09 schwarzgerat kernel: [038] 18 19 17 19 19 19 19 18    43 44 45 46 48 49 4b 4e
Sep 02 16:10:09 schwarzgerat kernel: [039] bd be be be be be be bd    be be bd bd bd be be be
Sep 02 16:10:09 schwarzgerat kernel: [040] cd 1d 5c 8b 70 30 08 fa    53 69 fe df e0 30 64 86
Sep 02 16:10:09 schwarzgerat kernel: [041] 42 42 42 42 42 42 42 42    41 41 41 41 41 41 41 41
Sep 02 16:10:09 schwarzgerat kernel: [042] 11 11 11 11 11 11 11 11    c9 c9 c9 c9 c9 c9 c9 c9
Sep 02 16:10:09 schwarzgerat kernel: [043] b5 b5 b5 b6 b6 b5 b5 b5    b5 b5 b5 b5 b5 b5 b5 b6
Sep 02 16:10:09 schwarzgerat kernel: [044] 31 a5 fc 3b 13 b7 7d 69    d6 f4 64 39 39 ad fa 2d
Sep 02 16:10:09 schwarzgerat kernel: [045] 5c 5c 5c 5c 5c 5c 5c 5c    5c 5c 5c 5c 5c 5c 5c 5c
Sep 02 16:10:09 schwarzgerat kernel: [046] 69 68 67 66 66 67 67 68    71 71 71 70 70 70 6f 6e
Sep 02 16:10:09 schwarzgerat kernel: [047] 7f 7f 7f 7f 7f 7f 7f 7f    7f 7f 7f 7f 7f 7f 7f 7f
Sep 02 16:10:09 schwarzgerat kernel: [048] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [049] 7f 7f 7f 7f 7f 7f 7f 7f    7f 7f 7f 7f 7f 7f 7f 7f
Sep 02 16:10:09 schwarzgerat kernel: [050] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [051] 7f 7f 7f 7f 7f 7f 7f 7f    7f 7f 7f 7f 7f 7f 7f 7f
Sep 02 16:10:09 schwarzgerat kernel: [052] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [053] 7f 7f 7f 7f 7f 7f 7f 7f    7f 7f 7f 7f 7f 7f 7f 7f
Sep 02 16:10:09 schwarzgerat kernel: [054] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [055] 7f 7f 7f 7f 7f 7f 7f 7f    7f 7f 7f 7f 7f 7f 7f 7f
Sep 02 16:10:09 schwarzgerat kernel: [056] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [057] 7f 7f 7f 7f 7f 7f 7f 7f    7f 7f 7f 7f 7f 7f 7f 7f
Sep 02 16:10:09 schwarzgerat kernel: [058] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [059] 7f 7f 7f 7f 7f 7f 7f 7f    7f 7f 7f 7f 7f 7f 7f 7f
Sep 02 16:10:09 schwarzgerat kernel: [060] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [061] 7f 7f 7f 7f 7f 7f 7f 7f    7f 7f 7f 7f 7f 7f 7f 7f
Sep 02 16:10:09 schwarzgerat kernel: [062] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [063] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [064] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [065] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [066] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [067] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [068] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [069] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [070] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [071] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [072] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [073] ac ac ab ab ac ac ac ac    50 50 50 50 51 50 50 50
Sep 02 16:10:09 schwarzgerat kernel: [074] 0c 00 f6 f6 00 07 11 1d    cf c3 ce f6 04 ec ef fc
Sep 02 16:10:09 schwarzgerat kernel: [075] 06 06 06 06 06 06 06 06    06 06 06 06 06 06 06 06
Sep 02 16:10:09 schwarzgerat kernel: [076] 43 43 43 43 43 43 43 43    4a 4a 4a 4a 4a 4a 4a 4a
Sep 02 16:10:09 schwarzgerat kernel: [077] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [078] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [079] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [080] fb fb fb fb fb fb fb fb    e1 e0 e1 e1 e0 e0 e0 e0
Sep 02 16:10:09 schwarzgerat kernel: [081] 03 03 03 03 03 03 03 03    08 08 08 08 08 08 08 08
Sep 02 16:10:09 schwarzgerat kernel: [082] fb fc fc fc fc fc fb fb    72 73 72 6e 6c 6f 6f 6d
Sep 02 16:10:09 schwarzgerat kernel: [083] 03 03 03 03 03 03 03 03    08 08 08 08 08 08 08 08
Sep 02 16:10:09 schwarzgerat kernel: [084] fb fc fc fc fc fc fb fb    72 73 72 6e 6c 6f 6f 6d
Sep 02 16:10:09 schwarzgerat kernel: [085] 0a 0a 0a 0a 0a 0a 0a 0a    09 09 09 09 09 09 09 09
Sep 02 16:10:09 schwarzgerat kernel: [086] 1a 1a 1a 1a 1a 1a 1a 1a    cc cb cb cb ca ca c9 c9
Sep 02 16:10:09 schwarzgerat kernel: [087] 0a 0a 0a 0a 0a 0a 0a 0a    09 09 09 09 09 09 09 09
Sep 02 16:10:09 schwarzgerat kernel: [088] 1f 1f 1f 1f 1f 1f 1f 1f    eb eb ea ea ea ea e9 e9
Sep 02 16:10:09 schwarzgerat kernel: [089] 27 27 27 27 27 27 27 27    27 27 27 27 27 27 27 27
Sep 02 16:10:09 schwarzgerat kernel: [090] 10 10 10 10 10 10 10 10    10 10 10 10 10 10 10 10
Sep 02 16:10:09 schwarzgerat kernel: [091] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [092] 04 04 04 04 04 04 04 04    4c 4f 4d 4d 4f 4f 4f 4f
Sep 02 16:10:09 schwarzgerat kernel: [093] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [094] 5f 5f 5f 5f 5f 5f 5f 5f    5d 5d 5d 5d 5d 5d 5d 5d
Sep 02 16:10:09 schwarzgerat kernel: [095] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [096] 59 59 59 59 59 59 59 59    5c 5c 5c 5c 5c 5c 5d 5d
Sep 02 16:10:09 schwarzgerat kernel: [097] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [098] d6 d7 d8 d9 d8 d7 d6 d6    d7 d8 d6 d6 d6 d7 d8 d8
Sep 02 16:10:09 schwarzgerat kernel: [099] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [100] ec ed ee ee ee ed ed ed    ed ed ec ec ec ed ee ee
Sep 02 16:10:09 schwarzgerat kernel: [101] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [102] 04 04 04 04 04 04 04 04    04 04 04 04 04 04 04 04
Sep 02 16:10:09 schwarzgerat kernel: [103] 30 30 30 30 30 30 30 30    30 30 30 30 30 30 30 30
Sep 02 16:10:09 schwarzgerat kernel: [104] c9 c9 c9 c9 c9 c9 c9 c9    ea ea eb eb eb eb eb eb
Sep 02 16:10:09 schwarzgerat kernel: [105] 0a 0a 0a 0a 0a 0a 0a 0a    0a 0a 0a 0a 0a 0a 0a 0a
Sep 02 16:10:09 schwarzgerat kernel: [106] 76 77 77 77 77 77 77 77    77 77 77 77 77 77 77 77
Sep 02 16:10:09 schwarzgerat kernel: [107] ff 00 00 00 00 00 00 00    54 54 55 55 55 55 55 55
Sep 02 16:10:09 schwarzgerat kernel: [108] fc 0e 21 33 45 57 69 7c    8e b5 03 29 50 77 9d c5
Sep 02 16:10:09 schwarzgerat kernel: [109] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [110] 68 68 68 68 68 68 68 68    68 68 68 68 68 68 68 68
Sep 02 16:10:09 schwarzgerat kernel: [111] 66 67 67 67 67 67 67 67    6a 6a 6a 6a 6a 6a 6a 6a
Sep 02 16:10:09 schwarzgerat kernel: [112] ff 00 01 02 03 04 05 06    1a 1b 1d 1e 1f 20 21 22
Sep 02 16:10:09 schwarzgerat kernel: [113] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [114] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [115] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [116] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [117] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [118] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [119] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [120] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [121] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [122] 03 03 03 03 03 03 03 03    03 03 03 03 03 03 03 03
Sep 02 16:10:09 schwarzgerat kernel: [123] 33 38 37 32 29 2a 34 38    31 28 34 3a 34 31 28 2c
Sep 02 16:10:09 schwarzgerat kernel: [124] 00 00 00 00 01 01 01 00    00 00 01 01 01 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [125] e6 b1 b1 b2 3b 3b 3b eb    b1 b1 3b 3b 05 b1 b1 b1
Sep 02 16:10:09 schwarzgerat kernel: [126] 27 27 27 27 27 27 27 27    27 27 27 27 27 27 27 27
Sep 02 16:10:09 schwarzgerat kernel: [127] 10 10 10 10 10 10 10 10    10 10 10 10 10 10 10 10
Sep 02 16:10:09 schwarzgerat kernel: [128] 1d 1d 1d 1d 1d 1d 1d 1d    1d 1d 1d 1d 1d 1d 1d 1d
Sep 02 16:10:09 schwarzgerat kernel: [129] 4c 4c 4c 4c 4c 4c 4c 4c    4c 4c 4c 4c 4c 4c 4c 4c
Sep 02 16:10:09 schwarzgerat kernel: [130] b3 b3 b3 b3 b3 b3 b3 b3    b3 b3 b3 b3 b3 b3 b3 b3
Sep 02 16:10:09 schwarzgerat kernel: [131] 86 86 86 86 86 86 86 86    86 86 86 86 86 86 86 86
Sep 02 16:10:09 schwarzgerat kernel: [132] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [133] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [134] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [135] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [136] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [137] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [138] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [139] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [140] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [141] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [142] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [143] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [144] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [145] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [146] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [147] ff ff ff ff ff ff ff ff    ff ff ff ff ff ff ff ff
Sep 02 16:10:09 schwarzgerat kernel: [148] 0a 0a 0a 0a 0a 0a 0a 0a    09 09 09 09 09 09 09 09
Sep 02 16:10:09 schwarzgerat kernel: [149] 1a 1a 1a 1a 1a 1a 1a 1a    cc cb cb cb ca ca c9 c9
Sep 02 16:10:09 schwarzgerat kernel: [150] 0a 0a 0a 0a 0a 0a 0a 0a    09 09 09 09 09 09 09 09
Sep 02 16:10:09 schwarzgerat kernel: [151] 1f 1f 1f 1f 1f 1f 1f 1f    eb eb ea ea ea ea e9 e9
Sep 02 16:10:09 schwarzgerat kernel: [152] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [153] d6 d7 d8 d9 d8 d7 d6 d6    d7 d8 d6 d6 d6 d7 d8 d8
Sep 02 16:10:09 schwarzgerat kernel: [154] 01 01 01 01 01 01 01 01    01 01 01 01 01 01 01 01
Sep 02 16:10:09 schwarzgerat kernel: [155] ec ed ee ee ee ed ed ed    ed ed ec ec ec ed ee ee
Sep 02 16:10:09 schwarzgerat kernel: [156] 09 09 09 09 09 09 09 09    09 09 09 09 09 09 09 09
Sep 02 16:10:09 schwarzgerat kernel: [157] 70 70 70 70 70 70 70 70    65 65 65 65 65 65 65 65
Sep 02 16:10:09 schwarzgerat kernel: [158] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [159] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [160] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [161] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [162] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
Sep 02 16:10:09 schwarzgerat kernel: [163] 00 00 00 00 00 00 00 00    00 00 00 00 00 00 00 00
```

**Comment by dankamongmen** [comment]
`Calibrated flow [dL/h]: 2121`

so if we're talking deciliters, this is now correct! w00t!

**Comment by aleksamagicka** [comment]
Thanks! For the record, value at offset `81` is [internally called](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/pull/18/commits/80a8dc0a0f1a6f8b58ed13d0452d2e56fd1d222d#diff-b0eeb47bb02c97a51a04cecf13c9b19ee9a4bbea5c45ad9ceee2afaba29dc51fL127) `FlowWithoutUserCompensation`.

**Comment by dankamongmen** [comment]
> Thanks! For the record, value at offset `81` is [internally called](https://github.com/aleksamagicka/aquacomputer_d5next-hwmon/pull/18/commits/80a8dc0a0f1a6f8b58ed13d0452d2e56fd1d222d#diff-b0eeb47bb02c97a51a04cecf13c9b19ee9a4bbea5c45ad9ceee2afaba29dc51fL127) `FlowWithoutUserCompensation`.

ahhh might want to remove the "Calibrated" part from the description (i certainly did no calibration for this value) then

**Pull request merged**
